Clinker_HTEC_MG.out=MG.C3S_DRX:Alite (%);MG.C2S_DRX:Belite (%);MG.C4AF_DRX:Ferrite (%);MG.c_C3A_DRX:Alum cubic (%);MG.o_C3A_DRX:Alum ortho (%);MG.CaO_DRX:Lime (%);MG.CaOH2 _DRX:Portlandite (%);MG.MgO_DRX:Periclase (%);MG.K2SO4_DRX:Arcanite (%);MG.Alphthitalite_DRX:Aphthitalite (%);MG.Langbeinite_DRX:Langbeinite (%)
Clinker_HTEC_MG.outID=Sample Name
